export type IconName = 
  | "pi-minus-circle" | "pi-circle-on" | "pi-circle-off" | "pi-sort-down" 
  | "pi-sort-up" | "pi-sort" | "pi-step-backward" | "pi-step-forward"
  | "pi-th-large" | "pi-arrow-down" | "pi-arrow-left" | "pi-arrow-right"
  | "pi-prime" | "pi-chart-pie" | "pi-reddit" | "pi-code" | "pi-sync"
  | "pi-shopping-bag" | "pi-server" | "pi-database" | "pi-hashtag"
  | "pi-bookmark-fill" | "pi-filter-fill" | "pi-heart-fill" | "pi-flag-fill"
  | "pi-sign-out" | "pi-wifi" | "pi-sitemap" | "pi-chart-bar" | "pi-camera"
  | "pi-dollar" | "pi-lock-open" | "pi-table" | "pi-map-marker" | "pi-list"
  | "pi-eye-slash" | "pi-eye" | "pi-folder-open" | "pi-building-columns"
  | "pi-file-check" | "pi-microchip-ai" | "pi-trophy" | "pi-barcode"
  | "pi-file-arrow-up" | "pi-mars" | "pi-tiktok"
  | "pi-arrow-up-right-and-arrow-down-left-from-center"
  | "pi-ethereum" | "pi-list-check" | "pi-thumbtack"
  | "pi-arrow-down-left-and-arrow-up-right-to-center"
  | "pi-linkedin" | "pi-send" | "pi-slack" | "pi-sun" | "pi-moon"
  | "pi-vimeo" | "pi-youtube" | "pi-flag" | "pi-wallet" | "pi-map"
  | "pi-link" | "pi-credit-card" | "pi-discord" | "pi-play" | "pi-compass"
  | "pi-id-card" | "pi-ticket" | "pi-file-o" | "pi-reply" | "pi-directions-alt"
  | "pi-directions" | "pi-thumbs-up" | "pi-thumbs-down"
  | "pi-sort-numeric-down-alt" | "pi-sort-numeric-up-alt"
  | "pi-sort-alpha-down-alt" | "pi-ellipsis-h" | "pi-bookmark" | "pi-globe"
  | "pi-replay" | "pi-filter" | "pi-print" | "pi-align-right"
  | "pi-align-left" | "pi-align-center" | "pi-align-justify" | "pi-cog"
  | "pi-cloud-download" | "pi-cloud-upload" | "pi-chevron-circle-up"
  | "pi-angle-double-down" | "pi-angle-double-left" | "pi-angle-double-right"
  | "pi-angle-double-up" | "pi-angle-down" | "pi-angle-left"
  | "pi-angle-right" | "pi-angle-up" | "pi-upload" | "pi-download" | "pi-ban"
  | "pi-search-minus" | "pi-file-excel" | "pi-file-pdf" | "pi-check-square"
  | "pi-chart-line" | "pi-user-edit" | "pi-exclamation-circle"
  | "pi-android" | "pi-google" | "pi-apple" | "pi-microsoft"
  | "pi-heart" | "pi-mobile" | "pi-bitcoin" | "pi-undo" | "pi-desktop";
